"""Result exporters for SciSeek."""

from __future__ import annotations

import csv
import html
import json
import re
from pathlib import Path

from sciseek.core.models import DocumentResult, SearchConfig


def unique_output_path(directory: Path, stem: str, suffix: str) -> Path:
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / f"{stem}{suffix}"
    if not path.exists():
        return path
    idx = 1
    while True:
        candidate = directory / f"{stem}_{idx}{suffix}"
        if not candidate.exists():
            return candidate
        idx += 1


def export_markdown(path: Path, results: list[DocumentResult], cfg: SearchConfig) -> Path:
    with path.open("w", encoding="utf-8") as f:
        f.write("# SciSeek Results\n\n")
        f.write(f"- Root: {cfg.root}\n")
        f.write(f"- Mode: {cfg.mode.value}\n")
        f.write(f"- Formats: {', '.join(cfg.file_formats)}\n")
        f.write(f"- Documents matched: {len(results)}\n\n")
        f.write("| File | Format | Terms | Occurrences |\n")
        f.write("|---|---|---|---|\n")
        for doc in results:
            escaped_name = doc.file_path.name.replace("|", "\\|")
            terms = ", ".join(doc.matched_terms).replace("|", "\\|")
            f.write(f"| {escaped_name} | {doc.format_type} | {terms} | {doc.match_count} |\n")
    return path


def export_csv(path: Path, results: list[DocumentResult], cfg: SearchConfig) -> Path:
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["file", "path", "format", "terms", "occurrences", "snippets"])
        for doc in results:
            snippets = " || ".join(o.snippet for o in doc.occurrences if o.snippet)
            writer.writerow([
                doc.file_path.name,
                str(doc.file_path),
                doc.format_type,
                "; ".join(doc.matched_terms),
                doc.match_count,
                snippets,
            ])
    return path


def export_json(path: Path, results: list[DocumentResult], cfg: SearchConfig) -> Path:
    payload = {
        "root": str(cfg.root),
        "mode": cfg.mode.value,
        "formats": cfg.file_formats,
        "results": [
            {
                "file": d.file_path.name,
                "path": str(d.file_path),
                "format": d.format_type,
                "terms": d.matched_terms,
                "occurrences": [
                    {"term": o.term, "count": o.count, "snippet": o.snippet, "page": o.page, "line": o.line}
                    for o in d.occurrences
                ],
                "match_count": d.match_count,
                "metadata": d.metadata,
            }
            for d in results
        ],
    }
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    return path


def export_html(path: Path, results: list[DocumentResult], cfg: SearchConfig) -> Path:
    rows = []
    for d in results:
        rows.append(
            "<tr>"
            f"<td>{html.escape(d.file_path.name)}</td>"
            f"<td>{html.escape(str(d.file_path))}</td>"
            f"<td>{html.escape(d.format_type)}</td>"
            f"<td>{html.escape(', '.join(d.matched_terms))}</td>"
            f"<td>{d.match_count}</td>"
            "</tr>"
        )
    content = """
<!DOCTYPE html>
<html lang="pt-BR">
<head><meta charset="UTF-8"><title>SciSeek Results</title></head>
<body>
<h1>SciSeek Results</h1>
<p><strong>Root:</strong> {root}</p>
<p><strong>Mode:</strong> {mode}</p>
<table border="1" cellspacing="0" cellpadding="6">
<thead><tr><th>Arquivo</th><th>Caminho</th><th>Formato</th><th>Termos</th><th>Ocorrencias</th></tr></thead>
<tbody>
{rows}
</tbody>
</table>
</body>
</html>
""".strip().format(root=html.escape(str(cfg.root)), mode=html.escape(cfg.mode.value), rows="\n".join(rows))
    path.write_text(content, encoding="utf-8")
    return path


def _bibtex_escape(value: str) -> str:
    return value.replace("{", "\\{").replace("}", "\\}")


def _slug_key(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", text.lower())[:32] or "item"


def _get_meta(metadata: dict[str, object], *keys: str) -> str:
    lowered = {str(k).lower(): v for k, v in metadata.items()}
    for key in keys:
        value = lowered.get(key.lower())
        if isinstance(value, str) and value.strip():
            return value.strip()
        if isinstance(value, list) and value:
            parts = [str(x).strip() for x in value if str(x).strip()]
            if parts:
                return " and ".join(parts)
    return ""


def export_bibtex_partial(path: Path, results: list[DocumentResult], cfg: SearchConfig) -> Path:
    lines: list[str] = ["% Partial BibTeX generated by SciSeek"]
    for idx, doc in enumerate(results, start=1):
        meta = doc.metadata or {}
        title = _get_meta(meta, "title") or doc.file_path.stem
        author = _get_meta(meta, "author", "authors", "creator")
        year = _get_meta(meta, "year", "published", "date")
        doi = _get_meta(meta, "doi")

        base_key = _slug_key(author.split(" and ")[0] if author else doc.file_path.stem)
        year_key = re.search(r"\d{4}", year)
        key = f"{base_key}{year_key.group(0) if year_key else idx}"

        lines.append(f"@misc{{{key},")
        lines.append(f"  title = {{{_bibtex_escape(title)}}},")
        if author:
            lines.append(f"  author = {{{_bibtex_escape(author)}}},")
        if year:
            lines.append(f"  year = {{{_bibtex_escape(year)}}},")
        if doi:
            lines.append(f"  doi = {{{_bibtex_escape(doi)}}},")
        lines.append(f"  file = {{{_bibtex_escape(str(doc.file_path))}}},")
        lines.append(f"  note = {{Exported by SciSeek ({cfg.mode.value})}},")
        lines.append("}")
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")
    return path
